package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.Room;
import org.mybatis.cdi.Mapper;

@Mapper
public interface RoomMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ROOM
     *
     * @mbg.generated Sat Mar 18 18:56:57 EET 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ROOM
     *
     * @mbg.generated Sat Mar 18 18:56:57 EET 2017
     */
    int insert(Room record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ROOM
     *
     * @mbg.generated Sat Mar 18 18:56:57 EET 2017
     */
    Room selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ROOM
     *
     * @mbg.generated Sat Mar 18 18:56:57 EET 2017
     */
    List<Room> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ROOM
     *
     * @mbg.generated Sat Mar 18 18:56:57 EET 2017
     */
    int updateByPrimaryKey(Room record);
}