package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.StudentHistory;
import org.mybatis.cdi.Mapper;

@Mapper
public interface StudentHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDENT_HISTORY
     *
     * @mbg.generated Sat Mar 18 18:56:57 EET 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDENT_HISTORY
     *
     * @mbg.generated Sat Mar 18 18:56:57 EET 2017
     */
    int insert(StudentHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDENT_HISTORY
     *
     * @mbg.generated Sat Mar 18 18:56:57 EET 2017
     */
    StudentHistory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDENT_HISTORY
     *
     * @mbg.generated Sat Mar 18 18:56:57 EET 2017
     */
    List<StudentHistory> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDENT_HISTORY
     *
     * @mbg.generated Sat Mar 18 18:56:57 EET 2017
     */
    int updateByPrimaryKey(StudentHistory record);
}