package lt.vu.mybatis.model;

import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class Room {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ROOM.ID
     *
     * @mbg.generated Sat Mar 18 18:56:57 EET 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ROOM.NAME
     *
     * @mbg.generated Sat Mar 18 18:56:57 EET 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ROOM.DORMITORY_ID
     *
     * @mbg.generated Sat Mar 18 18:56:57 EET 2017
     */
    private Integer dormitoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ROOM.MAX_PEOPLE
     *
     * @mbg.generated Sat Mar 18 18:56:57 EET 2017
     */
    private Integer maxPeople;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ROOM.ID
     *
     * @return the value of PUBLIC.ROOM.ID
     *
     * @mbg.generated Sat Mar 18 18:56:57 EET 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ROOM.ID
     *
     * @param id the value for PUBLIC.ROOM.ID
     *
     * @mbg.generated Sat Mar 18 18:56:57 EET 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ROOM.NAME
     *
     * @return the value of PUBLIC.ROOM.NAME
     *
     * @mbg.generated Sat Mar 18 18:56:57 EET 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ROOM.NAME
     *
     * @param name the value for PUBLIC.ROOM.NAME
     *
     * @mbg.generated Sat Mar 18 18:56:57 EET 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ROOM.DORMITORY_ID
     *
     * @return the value of PUBLIC.ROOM.DORMITORY_ID
     *
     * @mbg.generated Sat Mar 18 18:56:57 EET 2017
     */
    public Integer getDormitoryId() {
        return dormitoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ROOM.DORMITORY_ID
     *
     * @param dormitoryId the value for PUBLIC.ROOM.DORMITORY_ID
     *
     * @mbg.generated Sat Mar 18 18:56:57 EET 2017
     */
    public void setDormitoryId(Integer dormitoryId) {
        this.dormitoryId = dormitoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ROOM.MAX_PEOPLE
     *
     * @return the value of PUBLIC.ROOM.MAX_PEOPLE
     *
     * @mbg.generated Sat Mar 18 18:56:57 EET 2017
     */
    public Integer getMaxPeople() {
        return maxPeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ROOM.MAX_PEOPLE
     *
     * @param maxPeople the value for PUBLIC.ROOM.MAX_PEOPLE
     *
     * @mbg.generated Sat Mar 18 18:56:57 EET 2017
     */
    public void setMaxPeople(Integer maxPeople) {
        this.maxPeople = maxPeople;
    }
}