package lt.vu.mybatis.model;

import lombok.Getter;
import lombok.Setter;

import java.util.List;

@Getter
@Setter
public class Student {

    // Rankomis prirašyti:
    private Room room;
    private StudentHistory history;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT.ID
     *
     * @mbg.generated Sat Mar 18 18:56:57 EET 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT.FIRST_NAME
     *
     * @mbg.generated Sat Mar 18 18:56:57 EET 2017
     */
    private String firstName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT.LAST_NAME
     *
     * @mbg.generated Sat Mar 18 18:56:57 EET 2017
     */
    private String lastName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT.DORMITORY_ID
     *
     * @mbg.generated Sat Mar 18 18:56:57 EET 2017
     */
    private Integer dormitoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT.ROOM_ID
     *
     * @mbg.generated Sat Mar 18 18:56:57 EET 2017
     */
    private Integer roomId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT.HISTORY_ID
     *
     * @mbg.generated Sat Mar 18 18:56:57 EET 2017
     */
    private Integer historyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT.REGISTRATION_NO
     *
     * @mbg.generated Sat Mar 18 18:56:57 EET 2017
     */
    private String registrationNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENT.ID
     *
     * @param id the value for PUBLIC.STUDENT.ID
     *
     * @mbg.generated Sat Mar 18 18:56:57 EET 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENT.FIRST_NAME
     *
     * @param firstName the value for PUBLIC.STUDENT.FIRST_NAME
     *
     * @mbg.generated Sat Mar 18 18:56:57 EET 2017
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENT.LAST_NAME
     *
     * @param lastName the value for PUBLIC.STUDENT.LAST_NAME
     *
     * @mbg.generated Sat Mar 18 18:56:57 EET 2017
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENT.DORMITORY_ID
     *
     * @param dormitoryId the value for PUBLIC.STUDENT.DORMITORY_ID
     *
     * @mbg.generated Sat Mar 18 18:56:57 EET 2017
     */
    public void setDormitoryId(Integer dormitoryId) {
        this.dormitoryId = dormitoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENT.ROOM_ID
     *
     * @param roomId the value for PUBLIC.STUDENT.ROOM_ID
     *
     * @mbg.generated Sat Mar 18 18:56:57 EET 2017
     */
    public void setRoomId(Integer roomId) {
        this.roomId = roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENT.HISTORY_ID
     *
     * @param historyId the value for PUBLIC.STUDENT.HISTORY_ID
     *
     * @mbg.generated Sat Mar 18 18:56:57 EET 2017
     */
    public void setHistoryId(Integer historyId) {
        this.historyId = historyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENT.REGISTRATION_NO
     *
     * @param registrationNo the value for PUBLIC.STUDENT.REGISTRATION_NO
     *
     * @mbg.generated Sat Mar 18 18:56:57 EET 2017
     */
    public void setRegistrationNo(String registrationNo) {
        this.registrationNo = registrationNo;
    }
}