package lt.vu.mybatis.model;

public class StudentHistory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT_HISTORY.ID
     *
     * @mbg.generated Sat Mar 18 18:56:57 EET 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT_HISTORY.HISTORY
     *
     * @mbg.generated Sat Mar 18 18:56:57 EET 2017
     */
    private String history;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENT_HISTORY.ID
     *
     * @return the value of PUBLIC.STUDENT_HISTORY.ID
     *
     * @mbg.generated Sat Mar 18 18:56:57 EET 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENT_HISTORY.ID
     *
     * @param id the value for PUBLIC.STUDENT_HISTORY.ID
     *
     * @mbg.generated Sat Mar 18 18:56:57 EET 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENT_HISTORY.HISTORY
     *
     * @return the value of PUBLIC.STUDENT_HISTORY.HISTORY
     *
     * @mbg.generated Sat Mar 18 18:56:57 EET 2017
     */
    public String getHistory() {
        return history;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENT_HISTORY.HISTORY
     *
     * @param history the value for PUBLIC.STUDENT_HISTORY.HISTORY
     *
     * @mbg.generated Sat Mar 18 18:56:57 EET 2017
     */
    public void setHistory(String history) {
        this.history = history;
    }
}