package deivydas.mybatis.model;

public class StudyProgram {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDY_PROGRAM.ID
     *
     * @mbg.generated Sat Mar 25 11:19:21 EET 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDY_PROGRAM.TITLE
     *
     * @mbg.generated Sat Mar 25 11:19:21 EET 2017
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDY_PROGRAM.FACULTY
     *
     * @mbg.generated Sat Mar 25 11:19:21 EET 2017
     */
    private String faculty;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDY_PROGRAM.ID
     *
     * @return the value of PUBLIC.STUDY_PROGRAM.ID
     *
     * @mbg.generated Sat Mar 25 11:19:21 EET 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDY_PROGRAM.ID
     *
     * @param id the value for PUBLIC.STUDY_PROGRAM.ID
     *
     * @mbg.generated Sat Mar 25 11:19:21 EET 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDY_PROGRAM.TITLE
     *
     * @return the value of PUBLIC.STUDY_PROGRAM.TITLE
     *
     * @mbg.generated Sat Mar 25 11:19:21 EET 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDY_PROGRAM.TITLE
     *
     * @param title the value for PUBLIC.STUDY_PROGRAM.TITLE
     *
     * @mbg.generated Sat Mar 25 11:19:21 EET 2017
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDY_PROGRAM.FACULTY
     *
     * @return the value of PUBLIC.STUDY_PROGRAM.FACULTY
     *
     * @mbg.generated Sat Mar 25 11:19:21 EET 2017
     */
    public String getFaculty() {
        return faculty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDY_PROGRAM.FACULTY
     *
     * @param faculty the value for PUBLIC.STUDY_PROGRAM.FACULTY
     *
     * @mbg.generated Sat Mar 25 11:19:21 EET 2017
     */
    public void setFaculty(String faculty) {
        this.faculty = faculty;
    }
}