CREATE TABLE IF NOT EXISTS DORMITORY
(
  ID INTEGER NOT NULL IDENTITY,
  STREET            VARCHAR(50),
  STREET_NUMBER INTEGER,
  OPT_LOCK_VERSION INTEGER,
  PRIMARY KEY (ID)
);
CREATE TABLE IF NOT EXISTS ROOM
(
	ID INTEGER NOT NULL IDENTITY,
	NAME             VARCHAR(4),
	OPT_LOCK_VERSION INTEGER,
	DORMITORY_ID INTEGER,
	MAX_PEOPLE INTEGER,
	PRIMARY KEY (ID),
	FOREIGN KEY (DORMITORY_ID) REFERENCES DORMITORY (ID),
);
CREATE TABLE IF NOT EXISTS STUDY_PROGRAM
(
	ID INTEGER NOT NULL IDENTITY,
	TITLE             VARCHAR(250),
	FACULTY						VARCHAR(250),
	OPT_LOCK_VERSION INTEGER,
	PRIMARY KEY (ID),
);
CREATE TABLE IF NOT EXISTS STUDENT
(
	ID INTEGER NOT NULL IDENTITY,
	FIRST_NAME       VARCHAR(20),
	LAST_NAME        VARCHAR(20),
	DORMITORY_ID     INTEGER,
	ROOM_ID 				 INTEGER,
	STUDY_PROGRAM_ID			 INTEGER,
	REGISTRATION_NO  VARCHAR(20),
	OPT_LOCK_VERSION INTEGER,
	PRIMARY KEY (ID),
	FOREIGN KEY (DORMITORY_ID) REFERENCES DORMITORY (ID),
	FOREIGN KEY (ROOM_ID) REFERENCES ROOM (ID),
	FOREIGN KEY (STUDY_PROGRAM_ID) REFERENCES STUDY_PROGRAM(ID)
);

CREATE TABLE IF NOT EXISTS STUDENT_STUDY_PROGRAM
(
  STUDENT_ID      INTEGER,
  STUDY_PROGRAM_ID       INTEGER,
  PRIMARY KEY (STUDENT_ID, STUDY_PROGRAM_ID),
  FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT (ID),
  FOREIGN KEY (STUDY_PROGRAM_ID) REFERENCES STUDY_PROGRAM (ID)
);
