package deivydas.mybatis.dao;

import deivydas.mybatis.model.StudyProgram;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface StudyProgramMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDY_PROGRAM
     *
     * @mbg.generated Sat Mar 25 11:19:21 EET 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDY_PROGRAM
     *
     * @mbg.generated Sat Mar 25 11:19:21 EET 2017
     */
    int insert(StudyProgram record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDY_PROGRAM
     *
     * @mbg.generated Sat Mar 25 11:19:21 EET 2017
     */
    StudyProgram selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDY_PROGRAM
     *
     * @mbg.generated Sat Mar 25 11:19:21 EET 2017
     */
    List<StudyProgram> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDY_PROGRAM
     *
     * @mbg.generated Sat Mar 25 11:19:21 EET 2017
     */
    int updateByPrimaryKey(StudyProgram record);
}